# Programming in Excel (i): Introduction to `LAMBDA`

## Curriculum

-   How to define your own functions using `LAMBDA` and why it is useful.

-   Using the name manager.

-   Introduction to the [Advanced Formula Environment](https://www.microsoft.com/en-us/garage/profiles/advanced-formula-environment-a-microsoft-garage-project/), with emphasis on how to write documented and reusable code using the module functionality.

-   Construction of custom arrays with `{}`.

-   What a [dynamic arrays](https://exceljet.net/articles/dynamic-array-formulas-in-excel), what the `#SPILL!` error means, and how to use dynamic arrays are ranges.

-   Extending the basic Excel functions with `MAP`, `BYROW`, `BYCOLUMN`.

-   Exercise in making custom functions using the tools we have learned until now.

-   Making random numbers using the function `RANDARRAY`.

## Lectures and exercises

The Excel sheets used in the lecture, before being filled in, [here](https://github.com/BI-DS/ELE-3915/blob/main/slides/lecture04.xlsx). The lecture notes after being filled in are [here](https://github.com/BI-DS/ELE-3915/blob/main/slides/lecture04_solutions.xlsx). [Here](https://github.com/BI-DS/ELE-3915/blob/main/exercises/exercises04.xlsx) are the exercises; the solutions can be found [here](https://github.com/BI-DS/ELE-3915/blob/main/exercises/exercises04_solutions.xlsx).

## Recommended resources
