project:
  type: book
  output-dir: docs

book:
  title: "Excel Programming and Automation"
  author: "Jonas Moss"
  date: "15.02.2022"
  search: false
  repo-url: https://github.com/bi-ds/EBA-3500/
  chapters:
    - index.qmd
    - 01-excelbasics-i.qmd
    - 02-excelbasics-ii.qmd
    - 03-excelbasics-iii.qmd
    - 04-dynamic-arrays.qmd
    - 05-lambdas-let.qmd
    - 06-lambdas-and-let-ii.qmd
    - 07-pivot-tables.qmd
    - 08-typescript-i.qmd
    - 09-typescript-ii.qmd
    - 10-typescript-iii.qmd
    - 11-typescript-iv.qmd
    - 12-typescript-excel.qmd

format:
  html:
    theme: zephyr
    highlight-style: nord

editor: visual

